### ISSUE TITLE
[Quality] Implement CI/CD Workflow

### ISSUE THREAD

**Issue by aj-geddes** [aj-geddes/terry-form-mcp#3]
## Overview

As part of the Repository Quality Implementation Plan, we need to implement a standardized CI/CD workflow for the Terry-Form MCP repository. This will ensure consistent code quality checks, automated testing, and reliable deployment processes for this critical Terraform MCP server.

### 1. GitHub Actions Workflow File

Create a comprehensive GitHub Actions workflow file at `.github/workflows/ci.yml`:

```yaml
name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check formatting with black
      run: |
        black --check .
    
    - name: Sort imports with isort
      run: |
        isort --check .
    
    - name: Type check with mypy
      run: |
        mypy terry_form_mcp tests
    
    - name: Security scan with bandit
      run: |
        bandit -r terry_form_mcp -c pyproject.toml
    
    - name: Test with pytest
      run: |
        pytest
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false

  terraform-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
    - name: Terraform Format Check
      run: |
        cd examples
        terraform fmt -check -recursive
    
    - name: Terraform Security Scan
      uses: triat/terraform-security-scan@v3
      with:
        tfsec_args: --soft-fail
    
    - name: Run tflint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1
    
    - name: Terraform Lint
      run: |
        cd examples
        tflint --init
        tflint --format=compact

  docker:
    runs-on: ubuntu-latest
    needs: [quality, terraform-validation]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=semver,pattern={{version}}
          type=ref,event=branch
          type=sha,format=short
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

### 2. Release Workflow

Create a release workflow at `.github/workflows/release.yml`:

```yaml
name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/git
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
```

### 3. Docker Image Publishing Workflow

Create a workflow for publishing Docker images at `.github/workflows/publish.yml`:

```yaml
name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

### 4. CodeCov Integration

1. Set up integration with [codecov.io](https://codecov.io/) for code coverage reporting
2. Add a `.codecov.yml` configuration file:

```yaml
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
```

### 5. Dependabot Configuration

Add a `.github/dependabot.yml` file:

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "automated"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "automated"
      - "dependencies"
  
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "automated"
      - "dependencies"
  
  - package-ecosystem: "terraform"
    directory: "/examples"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "automated"
      - "dependencies"
```

### 6. Pre-commit Configuration

Add a `.pre-commit-config.yaml` file:

```yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests, types-PyYAML]

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
```

## Acceptance Criteria

1. All CI/CD workflows run successfully on push to main branch and on pull requests
2. Code quality checks (linting, formatting, type checking, security scanning) are enforced
3. Terraform-specific validation is performed on example configurations
4. Tests run against Python 3.10, 3.11, and 3.12
5. Docker builds are verified automatically
6. Code coverage reports are generated and uploaded to codecov.io
7. Semantic release process creates proper version tags and release notes
8. Docker images are published to GitHub Container Registry with semantic versioning tags
9. Dependabot keeps dependencies up to date for Python, Docker, GitHub Actions, and Terraform

## Resources

- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Semantic Release Documentation](https://semantic-release.gitbook.io/semantic-release/)
- [CodeCov Documentation](https://docs.codecov.io/)
- [Dependabot Documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates)
- [Pre-commit Documentation](https://pre-commit.com/)

## Related Issues

- #2 Implement Comprehensive Testing Framework
